services:
  redis:
    container_name: redis
    image: redis

  proj.rabbitmq:
    container_name: "proj.rabbitmq"
    image: rabbitmq:management

  order.mssqldb:
    container_name: order.mssqldb
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"

  user.mssqldb:
    container_name: user.mssqldb
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"

  chat.mssqldb:
    container_name: chat.mssqldb
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"

  product.read.mongodb:
    container_name: product.read.mongodb
    image: mongo:latest

  product.update.mongodb:
    container_name: product.update.mongodb
    image: mongo:latest

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile

  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductsService/ProductsService.API/Dockerfile

  minio:
    container_name: minio
    image: minio/minio

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/UserService.API/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  chatservice:
    image: ${DOCKER_REGISTRY-}chatservice
    build:
      context: .
      dockerfile: ChatsService/ChatsService.API/Dockerfile
